apiVersion: apps/v1
kind: Deployment
metadata:
  name: add-non-exec-probes-later
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: add-non-exec-probes-later
  template:
    metadata:
      labels:
        app.kubernetes.io/name: add-non-exec-probes-later
    spec:
      containers:
      - name: main
        image: 'docker.io/library/nginx:latest'
        ports:
        - name: http
          containerPort: 80
