apiVersion: apps/v1
kind: Deployment
metadata:
  name: starts-with-probes
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: start-with-probes
  template:
    metadata:
      labels:
        app.kubernetes.io/name: start-with-probes
    spec:
      containers:
      - name: main
        image: 'busybox:latest'
        command:
        - 'sleep'
        - '999m'
        livenessProbe:
          exec:
            command:
            - 'true'
          timeoutSeconds: 2
